require('dotenv').config();
const path=require('path'),crypto=require('crypto'),express=require('express'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),helmet=require('helmet'),cors=require('cors'),rateLimit=require('express-rate-limit'),nodemailer=require('nodemailer'),twilio=require('twilio');
const {createCheckoutSession,verifyWebhook}=require('./payment/stripe');
const app=express(),PORT=process.env.PORT||10000,MONGODB_URI=process.env.MONGODB_URI,JWT_SECRET=process.env.JWT_SECRET;
const COMMERCIAL_EMAIL=process.env.QUOTE_NOTIFICATION_EMAIL||'KZTechnologies@gmail.com';
const allowedOrigins=new Set(['https://korcz4k.github.io','https://kzsite.onrender.com']),normalizeOrigin=v=>String(v||'').replace(/\/$/,'');
const corsOptions={origin(origin,cb){if(!origin||allowedOrigins.has(normalizeOrigin(origin)))return cb(null,true);cb(new Error('Origem não permitida pelo CORS.'));},methods:['GET','POST','OPTIONS'],allowedHeaders:['Content-Type','Authorization'],optionsSuccessStatus:204};
app.set('trust proxy',1);app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false}));app.use(cors(corsOptions));app.options('*',cors(corsOptions));
app.post('/api/payments/stripe/webhook',express.raw({type:'application/json',limit:'256kb'}),handleStripeWebhook);
app.use(express.json({limit:'256kb',strict:true}));app.use(express.urlencoded({extended:false,limit:'256kb'}));app.use(express.static(path.join(__dirname),{dotfiles:'deny',index:false,maxAge:'1h'}));
const limiter=(windowMs,max,message)=>rateLimit({windowMs,max,standardHeaders:true,legacyHeaders:false,message:{error:message}});
const apiLimiter=limiter(15*60*1000,100,'Muitas solicitações. Tente novamente mais tarde.'),loginLimiter=limiter(15*60*1000,10,'Muitas tentativas de login. Aguarde alguns minutos.'),registerLimiter=limiter(60*60*1000,5,'Muitas tentativas de cadastro. Tente novamente mais tarde.'),quoteLimiter=limiter(60*60*1000,10,'Muitas solicitações de orçamento. Tente novamente mais tarde.'),orderLimiter=limiter(60*60*1000,20,'Muitas tentativas de criação de pedido. Tente novamente mais tarde.'),checkoutLimiter=limiter(15*60*1000,20,'Muitas tentativas de pagamento. Aguarde alguns minutos.'),interestLimiter=limiter(60*60*1000,10,'Muitos formulários enviados. Tente novamente mais tarde.');app.use('/api',apiLimiter);
const verificationSchema=new mongoose.Schema({channel:{type:String,enum:['email','phone'],required:true},codeHash:{type:String,required:true,select:false},expiresAt:{type:Date,required:true},lastSentAt:{type:Date,required:true},attempts:{type:Number,default:0}},{_id:false});
const quoteSchema=new mongoose.Schema({quoteId:{type:String,required:true,unique:true,match:/^\d{15}$/},user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},nomeProponente:{type:String,required:true,trim:true,maxlength:160},email:{type:String,required:true,trim:true,lowercase:true,maxlength:254},telefone:{type:String,trim:true,maxlength:40},descricao:{type:String,required:true,maxlength:10000},quemAtendeu:{type:String,default:'Pendente',maxlength:160},empresaProjeto:{type:String,required:true,trim:true,maxlength:200},tipoOrcamento:{type:String,required:true,trim:true,maxlength:120},status:{type:String,enum:['novo','em_analise','respondido','arquivado'],default:'novo'}},{timestamps:true,collection:'orcamentos'});
const orderSchema=new mongoose.Schema({orderId:{type:String,required:true,unique:true,index:true},user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},productCode:{type:String,required:true},productName:{type:String,required:true,maxlength:160},amount:{type:Number,required:true,min:0},currency:{type:String,default:'BRL'},details:{type:String,trim:true,maxlength:5000,default:''},status:{type:String,enum:['pending_payment','paid','processing','completed','cancelled','refunded'],default:'pending_payment'},history:{type:[{status:{type:String,required:true},at:{type:Date,default:Date.now},note:{type:String,maxlength:500}}],default:[]},payment:{provider:{type:String,maxlength:80},preferenceId:{type:String,maxlength:200},paymentId:{type:String,maxlength:200},status:{type:String,maxlength:80},lastWebhookId:{type:String,maxlength:200}}},{timestamps:true,collection:'pedidos'});
const interestSchema=new mongoose.Schema({formId:{type:String,required:true,unique:true,index:true,match:/^\d{9}$/},user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},accountId:{type:String,required:true,index:true},email:{type:String,required:true,trim:true,lowercase:true,maxlength:254},telefone:{type:String,required:true,trim:true,maxlength:40},nomeCompleto:{type:String,required:true,trim:true,maxlength:180},regiao:{pais:{type:String,required:true,trim:true,maxlength:100},estado:{type:String,required:true,trim:true,maxlength:100},cidade:{type:String,required:true,trim:true,maxlength:100}},ondeConheceu:{type:String,required:true,trim:true,maxlength:200},expectativas:{type:String,trim:true,maxlength:5000,default:''}},{timestamps:true,collection:'lista de interessados'});
const userSchema=new mongoose.Schema({nome:{type:String,required:true,trim:true,maxlength:80},sobrenome:{type:String,required:true,trim:true,maxlength:100},userId:{type:String,required:true,unique:true,match:/^\d{9}$/,select:false},telefone:{type:String,required:true,trim:true,maxlength:40},email:{type:String,required:true,unique:true,trim:true,lowercase:true,maxlength:254},passwordHash:{type:String,required:true,select:false},role:{type:String,enum:['admin','cliente'],default:'cliente'},emailVerified:{type:Boolean,default:false},phoneVerified:{type:Boolean,default:false},verification:{type:[verificationSchema],default:[]},lastLoginAt:Date},{timestamps:true});
const Quote=mongoose.model('Quote',quoteSchema),Order=mongoose.model('Order',orderSchema),Interest=mongoose.model('Interest',interestSchema),User=mongoose.model('User',userSchema);
const PRODUCTS={'discord-essential':{name:'Bot Discord Essencial',amount:150},'discord-community':{name:'Bot Discord Comunidade',amount:300},'site-essential':{name:'Site Essencial',amount:250},'site-institutional':{name:'Site Institucional',amount:500},'landing-essential':{name:'Landing Page Essencial',amount:150}};
const cleanText=(v,m)=>String(v||'').trim().slice(0,m),publicUser=u=>({id:u._id,nome:u.nome,sobrenome:u.sobrenome,email:u.email,telefone:u.telefone,role:u.role,emailVerified:!!u.emailVerified,phoneVerified:!!u.phoneVerified});
function makeToken(u){return jwt.sign({sub:u._id.toString(),role:u.role},JWT_SECRET,{algorithm:'HS256',expiresIn:'7d',issuer:'korczak-technologies',audience:'korczak-client'});}function auth(){return async(req,res,next)=>{try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)return res.status(401).json({error:'Faça login para continuar.'});const p=jwt.verify(t,JWT_SECRET,{algorithms:['HS256'],issuer:'korczak-technologies',audience:'korczak-client'}),u=await User.findById(p.sub).select('+userId');if(!u)return res.status(401).json({error:'Sessão inválida.'});req.user=u;next();}catch{return res.status(401).json({error:'Sessão inválida ou expirada.'});}}}
async function generateId(Model,fn,field){for(let i=0;i<30;i++){const id=fn();if(!(await Model.exists({[field]:id})))return id;}throw Error('Falha ao gerar identificador.');}
const generateUserId=()=>generateId(User,()=>String(crypto.randomInt(100000000,1000000000)),'userId'),generateQuoteId=()=>generateId(Quote,()=>Array.from({length:15},()=>crypto.randomInt(0,10)).join(''),'quoteId'),generateOrderId=()=>generateId(Order,()=>`KZ-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,'orderId'),generateInterestId=()=>generateId(Interest,()=>String(crypto.randomInt(100000000,1000000000)),'formId');
function mapStripeStatus(status){const v=String(status||'').toLowerCase();if(v==='paid'||v==='succeeded')return'paid';if(['refunded','partially_refunded'].includes(v))return'refunded';if(['canceled','cancelled','unpaid','expired','requires_payment_method'].includes(v))return'cancelled';return'pending_payment';}
async function applyStripeUpdate(session,{webhookId}={}){const orderId=cleanText(session?.client_reference_id||session?.metadata?.orderId,100);if(!orderId)return null;const order=await Order.findOne({orderId});if(!order)return null;if(webhookId&&order.payment?.lastWebhookId===String(webhookId))return order;const paymentStatus=session.payment_status||session.status||'',nextStatus=mapStripeStatus(paymentStatus),paymentId=typeof session.payment_intent==='object'?String(session.payment_intent?.id||''):String(session.payment_intent||'');order.payment={provider:'stripe',preferenceId:String(session.id||order.payment?.preferenceId||''),paymentId,status:String(paymentStatus),lastWebhookId:webhookId?String(webhookId):order.payment?.lastWebhookId};if(order.status!==nextStatus){order.status=nextStatus;order.history.push({status:nextStatus,note:`Stripe: ${String(paymentStatus||'atualização de pagamento')}`});}await order.save();return order;}
async function handleStripeWebhook(req,res){try{const sig=req.headers['stripe-signature'];if(!sig)return res.status(400).json({error:'Assinatura ausente.'});const event=verifyWebhook(req.body,sig);if(!['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','checkout.session.expired'].includes(event.type))return res.sendStatus(200);const session=event.data.object;if(event.type==='checkout.session.async_payment_failed'||event.type==='checkout.session.expired')session.payment_status='cancelled';await applyStripeUpdate(session,{webhookId:event.id});res.sendStatus(200);}catch(error){console.error('ERRO_WEBHOOK_STRIPE',error.message);res.status(400).json({error:'Webhook inválido.'});}}
app.get('/health',(req,res)=>res.json({status:'ok',database:mongoose.connection.readyState===1?'connected':'disconnected',stripeConfigured:!!process.env.STRIPE_SECRET_KEY}));
app.post('/api/auth/register',registerLimiter,async(req,res)=>{try{const nome=cleanText(req.body?.nome,80),sobrenome=cleanText(req.body?.sobrenome,100),telefone=cleanText(req.body?.telefone,40),email=cleanText(req.body?.email,254).toLowerCase(),senha=String(req.body?.senha||'');if(!nome||!sobrenome||!telefone||!email||!senha)return res.status(400).json({error:'Preencha todos os campos.'});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Informe um e-mail válido.'});if(senha.length<8||senha.length>128)return res.status(400).json({error:'A senha deve ter entre 8 e 128 caracteres.'});if(await User.exists({email}))return res.status(409).json({error:'Este e-mail já está cadastrado.'});const userId=await generateUserId(),passwordHash=await bcrypt.hash(senha,12),firstUser=await User.countDocuments()===0,user=await User.create({nome,sobrenome,telefone,email,passwordHash,userId,role:firstUser?'admin':'cliente'});res.status(201).json({message:'Conta criada.',token:makeToken(user),user:publicUser(user)});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível criar a conta.'});}});
app.post('/api/auth/login',loginLimiter,async(req,res)=>{try{const email=cleanText(req.body?.email,254).toLowerCase(),senha=String(req.body?.senha||''),user=await User.findOne({email}).select('+passwordHash');if(!user||!(await bcrypt.compare(senha,user.passwordHash)))return res.status(401).json({error:'E-mail ou senha inválidos.'});user.lastLoginAt=new Date();await user.save();res.json({message:'Login realizado.',token:makeToken(user),user:publicUser(user)});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível realizar o login.'});}});
app.get('/api/me',auth(),async(req,res)=>{try{const quotes=await Quote.find({user:req.user._id}).sort({createdAt:-1}),orders=await Order.find({user:req.user._id}).sort({createdAt:-1});res.json({user:publicUser(req.user),quotes,orders});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível carregar os dados do cliente.'});}});
app.post('/api/interested',auth(),interestLimiter,async(req,res)=>{try{const nomeCompleto=cleanText(req.body?.nomeCompleto,180),email=cleanText(req.body?.email,254).toLowerCase(),telefone=cleanText(req.body?.telefone,40),pais=cleanText(req.body?.pais,100),estado=cleanText(req.body?.estado,100),cidade=cleanText(req.body?.cidade,100),ondeConheceu=cleanText(req.body?.ondeConheceu,200),expectativas=cleanText(req.body?.expectativas,5000);if(!nomeCompleto||!email||!telefone||!pais||!estado||!cidade||!ondeConheceu)return res.status(400).json({error:'Preencha todos os campos obrigatórios do formulário.'});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Informe um e-mail válido.'});const existing=await Interest.findOne({user:req.user._id});if(existing)return res.status(409).json({error:'Esta conta já está registrada na lista de interessados.',formId:existing.formId});const formId=await generateInterestId(),interest=await Interest.create({formId,user:req.user._id,accountId:req.user._id.toString(),email,telefone,nomeCompleto,regiao:{pais,estado,cidade},ondeConheceu,expectativas});res.status(201).json({message:'Seu interesse foi registrado com sucesso.',formId:interest.formId});}catch(e){console.error('ERRO_LISTA_INTERESSADOS',e);res.status(500).json({error:'Não foi possível registrar seu interesse.'});}});
app.post('/api/quotes',auth(),quoteLimiter,async(req,res)=>{try{const empresaProjeto=cleanText(req.body?.empresa,200),tipoOrcamento=cleanText(req.body?.servico,120),descricao=cleanText(req.body?.projeto,10000);if(!empresaProjeto||!tipoOrcamento||!descricao)return res.status(400).json({error:'Preencha todos os campos do orçamento.'});const quoteId=await generateQuoteId(),q=await Quote.create({quoteId,user:req.user._id,nomeProponente:`${req.user.nome} ${req.user.sobrenome}`,email:req.user.email,telefone:req.user.telefone,descricao,empresaProjeto,tipoOrcamento});res.status(201).json({message:'Orçamento criado.',quoteId:q.quoteId,status:q.status});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível criar o orçamento.'});}});
app.post('/api/orders',auth(),orderLimiter,async(req,res)=>{try{const productCode=cleanText(req.body?.productCode,100),details=cleanText(req.body?.details,5000),product=PRODUCTS[productCode];if(!product)return res.status(400).json({error:'Produto inválido.'});const orderId=await generateOrderId(),order=await Order.create({orderId,user:req.user._id,productCode,productName:product.name,amount:product.amount,details,history:[{status:'pending_payment',note:'Pedido criado.'}]});res.status(201).json({orderId:order.orderId,status:order.status,amount:order.amount,currency:order.currency});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível criar o pedido.'});}});
app.post('/api/orders/:orderId/checkout',auth(),checkoutLimiter,async(req,res)=>{try{const order=await Order.findOne({orderId:req.params.orderId,user:req.user._id});if(!order)return res.status(404).json({error:'Pedido não encontrado.'});if(order.status!=='pending_payment')return res.status(400).json({error:'Este pedido não está disponível para pagamento.'});const session=await createCheckoutSession(order);order.payment={provider:'stripe',preferenceId:String(session.id||''),status:String(session.payment_status||'pending')};await order.save();res.json({checkoutUrl:session.url});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível iniciar o pagamento.'});}});
app.use((req,res)=>{if(req.path.startsWith('/api/'))return res.status(404).json({error:'Rota não encontrada.'});res.status(404).sendFile(path.join(__dirname,'404.html'));});
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:'Erro interno do servidor.'});});
if(!MONGODB_URI||!JWT_SECRET)throw Error('MONGODB_URI e JWT_SECRET são obrigatórios.');
mongoose.connect(MONGODB_URI).then(()=>{console.log('MongoDB conectado');app.listen(PORT,()=>console.log(`Servidor ativo na porta ${PORT}`));}).catch(e=>{console.error('Falha ao conectar ao MongoDB',e);process.exit(1);});