require('dotenv').config();
const path=require('path'),crypto=require('crypto'),express=require('express'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),helmet=require('helmet'),cors=require('cors'),rateLimit=require('express-rate-limit'),nodemailer=require('nodemailer'),twilio=require('twilio');
const {createCheckoutSession,verifyWebhook}=require('./payment/stripe');
const app=express(),PORT=process.env.PORT||10000,MONGODB_URI=process.env.MONGODB_URI,JWT_SECRET=process.env.JWT_SECRET;
const COMMERCIAL_EMAIL=process.env.QUOTE_NOTIFICATION_EMAIL||'KZTechnologies@gmail.com';
const allowedOrigins=new Set(['https://korcz4k.github.io','https://kzsite.onrender.com']),normalizeOrigin=v=>String(v||'').replace(/\/$/,'');
const corsOptions={origin(origin,cb){if(!origin||allowedOrigins.has(normalizeOrigin(origin)))return cb(null,true);cb(new Error('Origem não permitida pelo CORS.'));},methods:['GET','POST','OPTIONS'],allowedHeaders:['Content-Type','Authorization'],optionsSuccessStatus:204};
app.set('trust proxy',1);app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false,referrerPolicy:{policy:'strict-origin-when-cross-origin'},crossOriginResourcePolicy:{policy:'same-site'}}));app.use(cors(corsOptions));app.options('*',cors(corsOptions));
// Stripe exige o corpo bruto para validar a assinatura do webhook.
app.post('/api/payments/stripe/webhook',express.raw({type:'application/json',limit:'256kb'}),handleStripeWebhook);
app.use(express.json({limit:'256kb',strict:true}));app.use(express.urlencoded({extended:false,limit:'256kb'}));app.use(express.static(path.join(__dirname),{dotfiles:'deny',index:false,maxAge:'1h'}));
const limiter=(windowMs,max,message)=>rateLimit({windowMs,max,standardHeaders:true,legacyHeaders:false,message:{error:message}});
const apiLimiter=limiter(15*60*1000,100,'Muitas solicitações. Tente novamente mais tarde.'),loginLimiter=limiter(15*60*1000,10,'Muitas tentativas de login. Aguarde alguns minutos.'),registerLimiter=limiter(60*60*1000,5,'Muitas tentativas de cadastro. Tente novamente mais tarde.'),verificationLimiter=limiter(15*60*1000,10,'Muitas tentativas de verificação. Aguarde alguns minutos.'),quoteLimiter=limiter(60*60*1000,10,'Muitas solicitações de orçamento. Tente novamente mais tarde.'),orderLimiter=limiter(60*60*1000,20,'Muitas tentativas de criação de pedido. Tente novamente mais tarde.'),checkoutLimiter=limiter(15*60*1000,20,'Muitas tentativas de pagamento. Aguarde alguns minutos.');app.use('/api',apiLimiter);
const verificationSchema=new mongoose.Schema({channel:{type:String,enum:['email','phone'],required:true},codeHash:{type:String,required:true,select:false},expiresAt:{type:Date,required:true},lastSentAt:{type:Date,required:true},attempts:{type:Number,default:0}},{_id:false});
const quoteSchema=new mongoose.Schema({quoteId:{type:String,required:true,unique:true,match:/^\d{15}$/},user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},nomeProponente:{type:String,required:true,trim:true,maxlength:160},email:{type:String,required:true,trim:true,lowercase:true,maxlength:254},telefone:{type:String,trim:true,maxlength:40},descricao:{type:String,required:true,maxlength:10000},quemAtendeu:{type:String,default:'Pendente',maxlength:160},empresaProjeto:{type:String,required:true,trim:true,maxlength:200},tipoOrcamento:{type:String,required:true,trim:true,maxlength:120},status:{type:String,enum:['novo','em_analise','respondido','arquivado'],default:'novo'}},{timestamps:true,collection:'orcamentos'});
const orderSchema=new mongoose.Schema({orderId:{type:String,required:true,unique:true,index:true},user:{type:mongoose.Schema.Types.ObjectId,ref:'User',required:true,index:true},productCode:{type:String,required:true},productName:{type:String,required:true,maxlength:160},amount:{type:Number,required:true,min:0},currency:{type:String,default:'BRL'},details:{type:String,trim:true,maxlength:5000,default:''},status:{type:String,enum:['pending_payment','paid','processing','completed','cancelled','refunded'],default:'pending_payment'},history:{type:[{status:{type:String,required:true},at:{type:Date,default:Date.now},note:{type:String,maxlength:500}}],default:[]},payment:{provider:{type:String,maxlength:80},preferenceId:{type:String,maxlength:200},paymentId:{type:String,maxlength:200},status:{type:String,maxlength:80},lastWebhookId:{type:String,maxlength:200}}},{timestamps:true,collection:'pedidos'});
const userSchema=new mongoose.Schema({nome:{type:String,required:true,trim:true,maxlength:80},sobrenome:{type:String,required:true,trim:true,maxlength:100},userId:{type:String,required:true,unique:true,match:/^\d{9}$/,select:false},telefone:{type:String,required:true,trim:true,maxlength:40},email:{type:String,required:true,unique:true,trim:true,lowercase:true,maxlength:254},passwordHash:{type:String,required:true,select:false},role:{type:String,enum:['admin','cliente'],default:'cliente'},emailVerified:{type:Boolean,default:false},phoneVerified:{type:Boolean,default:false},verification:{type:[verificationSchema],default:[]},lastLoginAt:Date},{timestamps:true});
const Quote=mongoose.model('Quote',quoteSchema),Order=mongoose.model('Order',orderSchema),User=mongoose.model('User',userSchema);
const PRODUCTS={'discord-essential':{name:'Bot Discord Essencial',amount:150},'discord-community':{name:'Bot Discord Comunidade',amount:300},'site-essential':{name:'Site Essencial',amount:250},'site-institutional':{name:'Site Institucional',amount:500},'landing-essential':{name:'Landing Page Essencial',amount:150}};
const smtpPort=Number(process.env.SMTP_PORT||465),mailer=process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS?nodemailer.createTransport({host:process.env.SMTP_HOST,port:smtpPort,secure:process.env.SMTP_SECURE?process.env.SMTP_SECURE==='true':smtpPort===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null,sms=process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_PHONE_NUMBER?twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN):null;
const cleanText=(v,m)=>String(v||'').trim().slice(0,m),publicUser=u=>({id:u._id,nome:u.nome,sobrenome:u.sobrenome,email:u.email,telefone:u.telefone,role:u.role,emailVerified:!!u.emailVerified,phoneVerified:!!u.phoneVerified});
function makeToken(u){return jwt.sign({sub:u._id.toString(),role:u.role},JWT_SECRET,{algorithm:'HS256',expiresIn:'7d',issuer:'korczak-technologies',audience:'korczak-client'});}function auth(){return async(req,res,next)=>{try{const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');if(!t)return res.status(401).json({error:'Faça login para continuar.'});const p=jwt.verify(t,JWT_SECRET,{algorithms:['HS256'],issuer:'korczak-technologies',audience:'korczak-client'}),u=await User.findById(p.sub);if(!u)return res.status(401).json({error:'Sessão inválida.'});req.user=u;next();}catch{return res.status(401).json({error:'Sessão inválida ou expirada.'});}}}
async function generateId(Model,fn,field){for(let i=0;i<30;i++){const id=fn();if(!(await Model.exists({[field]:id})))return id;}throw Error('Falha ao gerar identificador.');}
const generateUserId=()=>generateId(User,()=>String(crypto.randomInt(100000000,1000000000)),'userId'),generateQuoteId=()=>generateId(Quote,()=>Array.from({length:15},()=>crypto.randomInt(0,10)).join(''),'quoteId'),generateOrderId=()=>generateId(Order,()=>`KZ-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString('hex').toUpperCase()}`,'orderId');
function verificationCode(){return String(crypto.randomInt(100000,1000000));}function masked(v,c){if(c==='email'){const[a,b]=v.split('@');return`${a.slice(0,2)}***@${b}`;}return`${v.slice(0,3)}****${v.slice(-2)}`;}
function mapStripeStatus(status){const v=String(status||'').toLowerCase();if(v==='paid'||v==='succeeded')return'paid';if(['refunded','partially_refunded'].includes(v))return'refunded';if(['canceled','cancelled','unpaid','expired','requires_payment_method'].includes(v))return'cancelled';return'pending_payment';}
async function applyStripeUpdate(session,{webhookId}={}){const orderId=cleanText(session?.client_reference_id||session?.metadata?.orderId,100);if(!orderId)return null;const order=await Order.findOne({orderId});if(!order)return null;if(webhookId&&order.payment?.lastWebhookId===String(webhookId))return order;const paymentStatus=session.payment_status||session.status||'',nextStatus=mapStripeStatus(paymentStatus),paymentId=typeof session.payment_intent==='object'?String(session.payment_intent?.id||''):String(session.payment_intent||'');const changed=order.status!==nextStatus||order.payment?.status!==String(paymentStatus)||order.payment?.paymentId!==paymentId;order.payment={provider:'stripe',preferenceId:String(session.id||order.payment?.preferenceId||''),paymentId,status:String(paymentStatus),lastWebhookId:webhookId?String(webhookId):order.payment?.lastWebhookId};if(changed){order.status=nextStatus;order.history.push({status:nextStatus,note:`Stripe: ${String(paymentStatus||'atualização de pagamento')}`});}await order.save();return order;}
async function handleStripeWebhook(req,res){try{const sig=req.headers['stripe-signature'];if(!sig)return res.status(400).json({error:'Assinatura ausente.'});const event=verifyWebhook(req.body,sig);if(!['checkout.session.completed','checkout.session.async_payment_succeeded','checkout.session.async_payment_failed','checkout.session.expired'].includes(event.type))return res.sendStatus(200);const session=event.data.object;if(event.type==='checkout.session.async_payment_failed'||event.type==='checkout.session.expired')session.payment_status='cancelled';await applyStripeUpdate(session,{webhookId:event.id});res.sendStatus(200);}catch(error){console.error('ERRO_WEBHOOK_STRIPE',error.message);res.status(400).json({error:'Webhook inválido.'});}}
async function sendVerification(user,channel){const now=Date.now(),existing=user.verification.find(v=>v.channel===channel);if(existing&&now-new Date(existing.lastSentAt).getTime()<60000)throw Object.assign(Error('Aguarde 1 minuto para reenviar o código.'),{status:429});const code=verificationCode(),codeHash=await bcrypt.hash(code,10),expiresAt=new Date(now+10*60*1000);if(channel==='email'){if(!mailer)throw Object.assign(Error('Serviço de e-mail ainda não foi configurado no servidor.'),{status:503});await mailer.sendMail({from:process.env.EMAIL_FROM||process.env.SMTP_USER,to:user.email,subject:'Código de verificação — Korczak Technologies',text:`Seu código de verificação é ${code}. Ele expira em 10 minutos.`});}else{if(!sms)throw Object.assign(Error('Serviço de SMS ainda não foi configurado no servidor.'),{status:503});await sms.messages.create({body:`Korczak Technologies: seu código de verificação é ${code}. Expira em 10 minutos.`,from:process.env.TWILIO_PHONE_NUMBER,to:user.telefone});}if(existing){existing.codeHash=codeHash;existing.expiresAt=expiresAt;existing.lastSentAt=new Date();existing.attempts=0;}else user.verification.push({channel,codeHash,lastSentAt:new Date(),expiresAt,attempts:0});await user.save();return masked(channel==='email'?user.email:user.telefone,channel);}
async function notifyNewQuote(q){if(!mailer){console.error('ERRO_EMAIL_ORCAMENTO: SMTP não configurado.');return;}try{await mailer.sendMail({from:process.env.EMAIL_FROM||process.env.SMTP_USER,to:COMMERCIAL_EMAIL,replyTo:q.email,subject:`Novo orçamento #${q.quoteId} — Korczak Technologies`,text:`Novo orçamento recebido.\n\nID: ${q.quoteId}\nCliente: ${q.nomeProponente}\nE-mail: ${q.email}\nTelefone: ${q.telefone||'Não informado'}\nEmpresa/Projeto: ${q.empresaProjeto}\nServiço: ${q.tipoOrcamento}\nAtendimento: ${q.quemAtendeu}\n\nDescrição:\n${q.descricao}`});}catch(e){console.error('ERRO_EMAIL_ORCAMENTO',e.message);}}
app.get('/health',(req,res)=>res.json({status:'ok',database:mongoose.connection.readyState===1?'connected':'disconnected',smtpConfigured:!!mailer,stripeConfigured:!!process.env.STRIPE_SECRET_KEY}));
app.post('/api/auth/register',registerLimiter,async(req,res)=>{try{const nome=cleanText(req.body?.nome,80),sobrenome=cleanText(req.body?.sobrenome,100),telefone=cleanText(req.body?.telefone,40),email=cleanText(req.body?.email,254).toLowerCase(),senha=String(req.body?.senha||'');if(!nome||!sobrenome||!telefone||!email||!senha)return res.status(400).json({error:'Preencha todos os campos.'});if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Informe um e-mail válido.'});if(senha.length<8||senha.length>128)return res.status(400).json({error:'A senha deve ter entre 8 e 128 caracteres.'});if(await User.exists({email}))return res.status(409).json({error:'Este e-mail já está cadastrado.'});const userId=await generateUserId(),passwordHash=await bcrypt.hash(senha,12),firstUser=await User.countDocuments()===0,user=await User.create({nome,sobrenome,telefone,email,passwordHash,userId,role:firstUser?'admin':'cliente'});res.status(201).json({message:'Conta criada.',token:makeToken(user),user:publicUser(user)});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível criar a conta.'});}});
app.post('/api/auth/login',loginLimiter,async(req,res)=>{try{const email=cleanText(req.body?.email,254).toLowerCase(),senha=String(req.body?.senha||''),user=await User.findOne({email}).select('+passwordHash');if(!user||!(await bcrypt.compare(senha,user.passwordHash)))return res.status(401).json({error:'E-mail ou senha inválidos.'});user.lastLoginAt=new Date();await user.save();res.json({message:'Login realizado.',token:makeToken(user),user:publicUser(user)});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível realizar o login.'});}});
app.get('/api/me',auth(),async(req,res)=>{try{const quotes=await Quote.find({user:req.user._id}).sort({createdAt:-1}).select('quoteId status quemAtendeu empresaProjeto tipoOrcamento descricao createdAt updatedAt'),orders=await Order.find({user:req.user._id}).sort({createdAt:-1}).select('orderId productName amount currency status createdAt updatedAt');res.json({user:publicUser(req.user),quotes,orders});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível carregar os dados do cliente.'});}});
app.post('/api/verification/send',auth(),verificationLimiter,async(req,res)=>{try{const channel=req.body.channel;if(!['email','phone'].includes(channel))return res.status(400).json({error:'Canal de verificação inválido.'});if(channel==='email'&&req.user.emailVerified)return res.json({message:'E-mail já verificado.'});if(channel==='phone'&&req.user.phoneVerified)return res.json({message:'Telefone já verificado.'});const destination=await sendVerification(req.user,channel);res.json({message:`Código enviado para ${destination}.`,cooldown:60});}catch(e){res.status(e.status||500).json({error:e.message||'Não foi possível enviar o código.'});}});
app.post('/api/verification/confirm',auth(),verificationLimiter,async(req,res)=>{try{const{channel,code}=req.body;if(!['email','phone'].includes(channel)||!/^[0-9]{6}$/.test(String(code||'')))return res.status(400).json({error:'Código inválido.'});const record=req.user.verification.find(v=>v.channel===channel);if(!record)return res.status(400).json({error:'Solicite um código primeiro.'});if(record.expiresAt<Date.now()){req.user.verification=req.user.verification.filter(v=>v.channel!==channel);await req.user.save();return res.status(400).json({error:'Código expirado. Solicite outro.'});}record.attempts=(record.attempts||0)+1;if(record.attempts>5){req.user.verification=req.user.verification.filter(v=>v.channel!==channel);await req.user.save();return res.status(429).json({error:'Muitas tentativas. Solicite um novo código.'});}if(!(await bcrypt.compare(String(code),record.codeHash))){await req.user.save();return res.status(400).json({error:'Código incorreto.'});}if(channel==='email')req.user.emailVerified=true;else req.user.phoneVerified=true;req.user.verification=req.user.verification.filter(v=>v.channel!==channel);await req.user.save();res.json({message:`${channel==='email'?'E-mail':'Telefone'} verificado com sucesso.`,user:publicUser(req.user)});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível verificar o código.'});}});
app.post('/api/quotes',auth(),quoteLimiter,async(req,res)=>{try{const empresa=cleanText(req.body?.empresa,200),servico=cleanText(req.body?.servico,120),projeto=cleanText(req.body?.projeto,10000);if(!empresa||!servico||!projeto)return res.status(400).json({error:'Preencha empresa ou projeto, serviço e descrição.'});const quoteId=await generateQuoteId(),quote=await Quote.create({quoteId,user:req.user._id,nomeProponente:`${req.user.nome} ${req.user.sobrenome}`,email:req.user.email,telefone:req.user.telefone,descricao:projeto,empresaProjeto:empresa,tipoOrcamento:servico});void notifyNewQuote(quote);res.status(201).json({message:'Orçamento salvo com sucesso no banco de dados.',quoteId:quote.quoteId,quemAtendeu:'Pendente'});}catch(e){console.error('ERRO_AO_SALVAR_ORCAMENTO',e);res.status(500).json({error:'Não foi possível registrar o orçamento.'});}});
app.post('/api/orders',auth(),orderLimiter,async(req,res)=>{try{const productCode=cleanText(req.body?.product,80),details=cleanText(req.body?.details,5000),product=PRODUCTS[productCode];if(!product)return res.status(400).json({error:'Produto inválido ou indisponível.'});const orderId=await generateOrderId(),order=await Order.create({orderId,user:req.user._id,productCode,productName:product.name,amount:product.amount,currency:'BRL',details,status:'pending_payment',history:[{status:'pending_payment',note:'Pedido criado e aguardando pagamento.'}]});res.status(201).json({message:'Pedido criado com sucesso.',order:{orderId:order.orderId,productName:order.productName,amount:order.amount,currency:order.currency,status:order.status}});}catch(e){console.error('ERRO_AO_CRIAR_PEDIDO',e);res.status(500).json({error:'Não foi possível criar o pedido.'});}});
app.post('/api/orders/:orderId/checkout',auth(),checkoutLimiter,async(req,res)=>{try{const order=await Order.findOne({orderId:req.params.orderId,user:req.user._id});if(!order)return res.status(404).json({error:'Pedido não encontrado.'});if(['paid','processing','completed'].includes(order.status))return res.status(409).json({error:'Este pedido não pode receber um novo pagamento.'});if(!process.env.STRIPE_SECRET_KEY)return res.status(503).json({error:'O pagamento ainda não foi configurado no servidor.'});const checkout=await createCheckoutSession(order.toObject(),{customerEmail:req.user.email});if(!checkout.checkoutUrl)return res.status(502).json({error:'A Stripe não retornou uma URL de pagamento.'});order.payment={provider:'stripe',preferenceId:checkout.sessionId,paymentId:order.payment?.paymentId,status:'checkout_created',lastWebhookId:order.payment?.lastWebhookId};order.history.push({status:'pending_payment',note:'Checkout da Stripe criado.'});await order.save();res.json({checkoutUrl:checkout.checkoutUrl,sessionId:checkout.sessionId,orderId:order.orderId});}catch(e){console.error('ERRO_AO_CRIAR_CHECKOUT',e);res.status(e.code==='STRIPE_NOT_CONFIGURED'?503:502).json({error:'Não foi possível iniciar o pagamento.'});}});
app.get('/api/orders/:orderId',auth(),async(req,res)=>{try{const order=await Order.findOne({orderId:req.params.orderId,user:req.user._id}).select('orderId productName amount currency details status history createdAt updatedAt');if(!order)return res.status(404).json({error:'Pedido não encontrado.'});res.json({order});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível consultar o pedido.'});}});
app.get('/api/orders',auth(),async(req,res)=>{try{res.json({orders:await Order.find({user:req.user._id}).sort({createdAt:-1}).select('orderId productName amount currency status createdAt updatedAt')});}catch(e){console.error(e);res.status(500).json({error:'Não foi possível carregar os pedidos.'});}});
app.use((err,req,res,next)=>{if(err?.message==='Origem não permitida pelo CORS.')return res.status(403).json({error:'Origem não permitida.'});console.error('REQUEST_ERROR',err);res.status(500).json({error:'Erro interno do servidor.'});});app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
async function start(){if(!MONGODB_URI)throw Error('Defina MONGODB_URI no Render.');if(!JWT_SECRET||JWT_SECRET.length<32)throw Error('Defina um JWT_SECRET forte com pelo menos 32 caracteres no Render.');await mongoose.connect(MONGODB_URI,{dbName:'KorczakTechSite'});console.log('MongoDB conectado');app.listen(PORT,'0.0.0.0',()=>console.log(`Servidor na porta ${PORT}`));}start().catch(e=>{console.error('startup_error',e);process.exit(1);});
